package ols

import "text/template"

// Files rendered into $SERVER_ROOT/conf/olspanel/. Names sort so that
// external apps come first, then vhosts, then the listeners that map them.
const (
	FileProcessors = "olspanel/00-extprocessors.conf"
	FileVHosts     = "olspanel/10-vhosts.conf"
	FileListeners  = "olspanel/20-listeners.conf"
)

var tplProcessors = template.Must(template.New("procs").Parse(`# Generated by olspanel - do not edit.
{{range .Processors}}
extprocessor {{.Name}} {
  type                    lsapi
  address                 UDS://tmp/lshttpd/{{.Name}}.sock
  maxConns                10
  env                     PHP_LSAPI_CHILDREN=10
  env                     PHP_LSAPI_MAX_REQUESTS=1000
  env                     LSAPI_AVOID_FORK=1
  initTimeout             60
  retryTimeout            0
  persistConn             1
  pcKeepAliveTimeout      1
  respBuffer              0
  autoStart               2
  path                    {{.LsphpBin}}
  backlog                 100
  instances               1
  extUser                 {{.User}}
  extGroup                {{.Group}}
  runOnStartUp            1
  priority                0
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           400
  procHardLimit           500
}
{{end}}
{{if .PMARoot}}
extprocessor pma_php {
  type                    lsapi
  address                 UDS://tmp/lshttpd/pma_php.sock
  maxConns                5
  env                     PHP_LSAPI_CHILDREN=5
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               2
  path                    {{.PMAPhpBin}}
  extUser                 nobody
  extGroup                nogroup
  memSoftLimit            1024M
  memHardLimit            1024M
  procSoftLimit           200
  procHardLimit           300
}
{{end}}
`))

var tplVHosts = template.Must(template.New("vhosts").Parse(`# Generated by olspanel - do not edit.
virtualhost _default {
  vhRoot                  {{.DefaultRoot}}
  configFile              $SERVER_ROOT/conf/vhosts/_default/vhconf.conf
  allowSymbolLink         0
  enableScript            0
  restrained              1
}
{{if .PMARoot}}
virtualhost _pma {
  vhRoot                  {{.PMARoot}}
  configFile              $SERVER_ROOT/conf/vhosts/_pma/vhconf.conf
  allowSymbolLink         0
  enableScript            1
  restrained              1
}
{{end}}
{{range .VHosts}}
virtualhost {{.Name}} {
  vhRoot                  {{.Root}}
  configFile              $SERVER_ROOT/conf/vhosts/{{.Name}}/vhconf.conf
  allowSymbolLink         2
  enableScript            {{if .Suspended}}0{{else}}1{{end}}
  restrained              1
  setUIDMode              2
  user                    {{.User}}
  group                   {{.Group}}
}
{{end}}
`))

var tplListeners = template.Must(template.New("listeners").Parse(`# Generated by olspanel - do not edit.
listener Default {
  address                 *:80
  secure                  0
  map                     _default *
{{- range .VHosts}}
  map                     {{.Name}} {{.Name}}{{range .Aliases}}, {{.}}{{end}}
{{- end}}
}

listener DefaultSSL {
  address                 *:443
  secure                  1
  keyFile                 {{.PanelKey}}
  certFile                {{.PanelCert}}
  certChain               1
  sslProtocol             24
  enableECDHE             1
  renegProtection         1
  sslSessionCache         1
  enableSpdy              15
  enableQuic              0
  map                     _default *
{{- range .VHosts}}
  map                     {{.Name}} {{.Name}}{{range .Aliases}}, {{.}}{{end}}
{{- end}}
}
{{if .PMARoot}}
listener pma {
  address                 127.0.0.1:8081
  secure                  0
  map                     _pma *
}
{{end}}
`))

var tplVHConf = template.Must(template.New("vhconf").Parse(`# Generated by olspanel for {{.Name}} - do not edit.
docRoot                   {{if .Suspended}}{{.SuspendRoot}}{{else}}$VH_ROOT/public_html{{end}}
vhDomain                  $VH_NAME
vhAliases                 {{range $i, $a := .Aliases}}{{if $i}}, {{end}}{{$a}}{{end}}
enableGzip                1
enableBr                  1

index  {
  useServer               0
  indexFiles              index.php, index.html, index.htm
  autoIndex               0
}

errorlog $VH_ROOT/logs/error.log {
  useServer               0
  logLevel                WARN
  rollingSize             10M
  keepDays                30
}

accesslog $VH_ROOT/logs/access.log {
  useServer               0
  logFormat               "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""
  logHeaders              5
  rollingSize             10M
  keepDays                30
  compressArchive         1
}

{{if not .Suspended}}
scripthandler  {
  add                     lsapi:{{.Processor}} php
}

phpIniOverride  {
  php_admin_value open_basedir "{{.OpenBase}}"
  php_admin_value upload_tmp_dir "$VH_ROOT/tmp"
  php_admin_value session.save_path "$VH_ROOT/tmp"
  php_value upload_max_filesize 64M
  php_value post_max_size 64M
  php_value memory_limit 256M
  php_value max_execution_time 120
}
{{end}}

context /.well-known/acme-challenge {
  location                {{.ACMEDir}}/.well-known/acme-challenge
  allowBrowse             1
  addDefaultCharset       off
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
  logLevel                0
{{- if and .ForceHTTPS .SSLCert}}
  rules                   <<<END_rules
RewriteCond %{HTTPS} !on
RewriteCond %{REQUEST_URI} !^/\.well-known/acme-challenge/
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
END_rules
{{- end}}
}
{{if .SSLCert}}
vhssl  {
  keyFile                 {{.SSLKey}}
  certFile                {{.SSLCert}}
  certChain               1
  sslProtocol             24
  enableECDHE             1
  renegProtection         1
  sslSessionCache         1
  enableSpdy              15
}
{{end}}
`))

var tplDefaultVHConf = template.Must(template.New("default").Parse(`# Generated by olspanel - do not edit.
docRoot                   $VH_ROOT/html
enableGzip                1
index  {
  useServer               0
  indexFiles              index.html
}
errorlog $SERVER_ROOT/logs/_default-error.log {
  useServer               0
  logLevel                WARN
  rollingSize             10M
}
context /.well-known/acme-challenge {
  location                {{.ACMEDir}}/.well-known/acme-challenge
  allowBrowse             1
}
`))

var tplPMAVHConf = template.Must(template.New("pma").Parse(`# Generated by olspanel - do not edit.
docRoot                   $VH_ROOT
enableGzip                1
index  {
  useServer               0
  indexFiles              index.php, index.html
}
errorlog $SERVER_ROOT/logs/_pma-error.log {
  useServer               0
  logLevel                WARN
  rollingSize             10M
}
scripthandler  {
  add                     lsapi:pma_php php
}
phpIniOverride  {
  php_admin_value open_basedir "$VH_ROOT:/tmp"
  php_value upload_max_filesize 128M
  php_value post_max_size 128M
  php_value memory_limit 512M
  php_value max_execution_time 300
}
rewrite  {
  enable                  0
}
`))
